services:
  database:
    container_name: database
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  elastic.search:
    container_name: elastic.search
    environment:
      - node.name=elastic.search
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - msec-net
    volumes:
      - share-data:/usr/share/elasticsearch/data 
    ports:
      - "9200:9200"

  redis.cache:
    container_name: redis.cache
    restart: always
    ports:
      - "6379:6379"
  
  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elastic.search:9200
      - ELASTICSEARCH_HOSTS=http://elastic.search:9200
    networks:
      - msec-net
    depends_on:
      - elastic.search
    ports:
      - "5601:5601"
    volumes:
      - kibana-data:/usr/share/kibana/data  # Persistent volume for Kibana

  merastore.user.api:
    container_name: merastore.user.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=database;Database=UserDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True"
      - "ElasticConfiguration:Uri=http://host.docker.internal:9200"
      - ASPNETCORE_URLS=http://+:8001
    ports:
      - "8001:8001"
    networks:
      - msec-net
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  merastore.product.api:
    container_name: merastore.product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=database;Database=ProductDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True"
      - ElasticConfiguration__Uri=http://host.docker.internal:9200
      - ASPNETCORE_URLS=http://+:8002
    ports:
      - "8002:8002"
    networks:
      - msec-net
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

volumes:
  share-data:
    driver: local
  kibana-data:  # Declare the volume for Kibana
    driver: local

networks:
  msec-net:
    driver: bridge
