
services:
  merastore.user.api:
    image: ${DOCKER_REGISTRY-}merastoreuserapi
    build:
      context: .
      dockerfile: src/User/MeraStore.User.Api/Dockerfile

  merastore.product.api:
    image: ${DOCKER_REGISTRY-}merastoreproductapi
    build:
      context: .
      dockerfile: src/Product/MeraStore.Product.Api/Dockerfile

  redis.cache:
    image: redis:latest

  database:
    image: mcr.microsoft.com/mssql/server:latest
  
  elastic.search:  
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
