//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeraStore.User.Shared.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeraStore.User.Shared.Common.Resources.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 502.
        /// </summary>
        internal static string BadGatewayError {
            get {
                return ResourceManager.GetString("BadGatewayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        internal static string BadRequestError {
            get {
                return ResourceManager.GetString("BadRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 409.
        /// </summary>
        internal static string ConflictError {
            get {
                return ResourceManager.GetString("ConflictError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 436.
        /// </summary>
        internal static string DataNotFoundError {
            get {
                return ResourceManager.GetString("DataNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 403.
        /// </summary>
        internal static string ForbiddenError {
            get {
                return ResourceManager.GetString("ForbiddenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 434.
        /// </summary>
        internal static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 431.
        /// </summary>
        internal static string InvalidFieldError {
            get {
                return ResourceManager.GetString("InvalidFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 432.
        /// </summary>
        internal static string InvalidFormatError {
            get {
                return ResourceManager.GetString("InvalidFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 430.
        /// </summary>
        internal static string MissingFieldError {
            get {
                return ResourceManager.GetString("MissingFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404.
        /// </summary>
        internal static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 501.
        /// </summary>
        internal static string NotImplementedError {
            get {
                return ResourceManager.GetString("NotImplementedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 435.
        /// </summary>
        internal static string RequestError {
            get {
                return ResourceManager.GetString("RequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 503.
        /// </summary>
        internal static string ServiceUnavailableError {
            get {
                return ResourceManager.GetString("ServiceUnavailableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 429.
        /// </summary>
        internal static string TooManyRequestsError {
            get {
                return ResourceManager.GetString("TooManyRequestsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401.
        /// </summary>
        internal static string UnauthorizedError {
            get {
                return ResourceManager.GetString("UnauthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 422.
        /// </summary>
        internal static string UnprocessableEntityError {
            get {
                return ResourceManager.GetString("UnprocessableEntityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 433.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
    }
}
